language: cpp
sudo: required

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
      - cmake-data
      - rpm

script:
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - cpack -G DEB
  - cpack -G RPM
  - cpack -G TGZ

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.deb build/*.rpm build/*.tar.gz build/*.zip
  skip_cleanup: true
  on:
    tags: true
